services:
  - type: web
    name: consumet-api # Name of the service
    env: docker
    repo: https://github.com/KamiDanji/consumet-api
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000
